config/routes.rb
Rails.application.routes.draw do
    resources :users, only: [:new, :create]
    resources :voters, only: [:new, :create, :edit, :update, :index]
    resources :voters do collection {post :import} end
    get 'calls', to:'calls#index', as: :calls
    get 'welcome/index'

    get 'login', to: 'sessions#new'
    post 'login', to: 'sessions#create'
    get 'welcome', to: 'welcome#index'

    get 'nextcall', to: 'calls#nextcall'
    get 'walkthrough', to: 'calls#walkthrough'

    get 'reset_calling_voters', to:'voters#reset_calling_voters'


    root 'welcome#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  before_create :create_uuid
  validates :email, presence: true, uniqueness: true
  validates :name, presence: true
  validates :email, uniqueness: { :case_sensitive => false }, format: { with: URI::MailTo::EMAIL_REGEXP }, length: {maximum: 256}
  validates :name, length: { in: 1..256, message: "must be between 1 and 256 characters long"}
  has_many :voters

  default_scope { order(created_at: :asc) }

  def self.create_user(auth_hash)
    User.create(
        email: auth_hash.info.email,
        name: auth_hash.info.name,
    )
  end

  def stats
      count = Voter.count
      called = Voter.where.not(status: "Not Called Yet").count

      return called.to_s+ "/"+count.to_s
  end


  def generate_token
    self.token = SecureRandom.urlsafe_base64
  end

  def create_uuid
    begin
      self.uuid = SecureRandom.uuid
    end while self.class.exists?(:uuid => uuid)
  end
end

app/models/voter.rb
class Voter < ApplicationRecord
    belongs_to :user


    def self.import(file)
        spreadsheet = Roo::Spreadsheet.open(file.original_filename).sheet(0)
        header = spreadsheet.row(1)
        (2..spreadsheet.last_row).each do |i|
            row = Hash[[header, spreadsheet.row(i)].transpose]
            voter = find_by_id(row["id"]) || new
            voter.attributes = row.to_hash
            voter.update(user_id: User.first.id)
            voter.save!
        end
    end

    def format_phone
        return self.phone.sub(/(\d{3})(\d{3})(\d{4})/, "\\1-\\2-\\3")
    end

    def contact
        if self.created_at == self.updated_at
            return ""
        else
            return self.updated_at.to_formatted_s(:short)
        end
    end

    def full_address
        return self.address + " " + self.city + ", " + self.state + " " + self.zip5
    end

    def name
        return self.first_name + " " + self.last_name
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    helper_method :current_user
    def current_user
      return unless cookies.signed[:permanent_user_id] || session[:user_id]
      #@current_user ||= (User.find(session[:user_id]) if session[:user_id])
      begin
        @current_user ||= User.find_by(uuid: cookies.signed[:permanent_user_id] || session[:user_id])
      rescue Mongoid::Errors::DocumentNotFound
        nil
      end
    end
end

app/controllers/calls_controller.rb
class CallsController < ApplicationController
    before_action :check_current_user
    def index

        if params[:voter_id]
            @voter = Voter.find(params[:voter_id])
        else
            @voter = current_user.voters.where(status: "Not Called Yet").first
            if !@voter
                redirect_to root_path, alert: "There are currently no voters to call. Please contact Pierce @ pierce.dejong45@gmail.com or (403) 619-2494"
            end
        end


    end


    private
    def check_current_user
        if !current_user
            redirect_to root_path
        end
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
  end

  def login
  end

  def index
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def new
        @user = User.new
    end

    def create
        if !(User.find_by(email: user_params[:email])) && !(User.find_by( phone: user_params[:phone]))
            @user = User.create(user_params)
            respond_to do |format|
                if @user.save
                    cookies.permanent.signed[:permanent_user_id] = @user.uuid
                    session[:user_id] = @user.uuid
                    voters = Voter.where(user_id: User.first.id).where(status: "Not Called Yet").limit(50)
                    if voters
                        voters.all.each do |v| v.update(user_id: @user.id) end
                    end

                    format.html { redirect_to root_path }
                else
                    format.html { render 'welcome/index' }
                    format.json { render json: @user.errors, status: :unprocessable_entity }
                end
            end
        else
            @user = User.find_by(email: user_params[:email], phone: user_params[:phone])
            if @user
                # Kepp the user signed in at all times
                cookies.permanent.signed[:permanent_user_id] = @user.uuid
                session[:user_id] = @user.uuid
                # Go back to root path
                redirect_to root_path
            else
                respond_to do |format|
                    format.html { render 'welcome/index' }
                    flash[:alert] = "This Email and Phone combination does not match any records. Please ensure you have entered both in correctly."
                end

            end

        end
    end




    private

    def user_params
        params.require(:user).permit(:email, :name, :phone)
    end

    def check_current_user
        if !current_user
            redirect_to root_path
        end
    end
end

app/controllers/voters_controller.rb
class VotersController < ApplicationController
    before_action :check_current_user
  def new
      @voter = Voter.new
  end

  def create
      @voter = Voter.create(new_voter_params)
      @voter.update(user_id: User.first.id)
      respond_to do |format|
          if @voter.save
              format.html { redirect_to voters_path }
          else
              format.html { render 'voters/new' }
              format.json { render json: @user.errors, status: :unprocessable_entity }
          end
      end
  end

  def reset_calling_voters
      @v = Voter.where(status: "Currently Calling").all.each do |v|
          v.update_column(:status, "Not Called Yet")
      end
      redirect_to voters_path
  end

  def index
      if current_user.admin
           @voters = Voter.all
      else
           # @voters = Voter.where(user_id: current_user.id)
            @voters = Voter.all
      end

  end

  def update
      voter = Voter.find(voter_params[:id])
      voter.update(status: voter_params[:status])
      voter.update(user_id: current_user.id)
      if(voter_params[:status] == "Correct Person")
          voter.update(support: voter_params[:support]+voter_params[:no_support])
          voter.update(sign: voter_params[:sign])
          if(voter_params[:address]=="update")
              voter.update(address: voter_params[:new_address])
              voter.update(city: voter_params[:city])
              voter.update(state: voter_params[:state])
              voter.update(zip5: voter_params[:zip5])
          end
          voter.update(volunteer: voter_params[:volunteer])
      end
      redirect_to nextcall_path
  end

  def import
      Voter.import(params[:file])
      redirect_to voters_path
  end


  private

  def voter_params
      params.require(:voter).permit(:email, :name, :phone, :status, :id, :sign, :support, :no_support, :address, :new_address, :volunteer, :city, :state, :zip5)
  end
  def new_voter_params
      params.require(:voter).permit(:email, :name, :phone, :address)
  end

  def check_current_user
      if !current_user
          redirect_to root_path
      end
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
      if current_user.nil?
          @user = User.new
      end

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/calls_helper.rb
module CallsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/voters_helper.rb
module VotersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/calls/nextcall.html.erb
<div class="welcome-card centered text-center">
    <div class="w-100 justify-content-center d-flex pb-4">
        <%=image_tag asset_path("logo.png"), id:"logo"%>
    </div>

    <h4 class="pb-4">Call Sheet Submitted!</h4>
    <div class="d-flex">
        <%= link_to "Make Another Call", calls_path, class:"btn btn-primary mr-3"%>
        <%= link_to "Take a Break", root_path, class:"btn btn-primary ml-3"%>
    </div>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Volunteer Calls - Rep. Lloyd Doggett</title>
    <meta content="width=device-width, initial-scale=1" name="viewport" />
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.1/css/all.css" integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr" crossorigin="anonymous">

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>


    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <html lang="en" xml:lang="en" xmlns= "http://www.w3.org/1999/xhtml">
    <meta charset="UTF-8">
    <meta name="google" content="notranslate">
    <meta http-equiv="Content-Language" content="en">
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/users/new.html.erb
<% unless current_user.nil? %>
<p id="alert" class="alert alert-primary text-center"><%= alert %></p>
<div class="welcome-card centered text-center">
    <div class="w-100 justify-content-center d-flex pb-4">
        <%=image_tag "/assets/logo.png", id:"logo"%>
    </div>
    <h4 class="pb-4">Hello <%=current_user.name%></h4>
    <%= link_to "Start Making Calls!", calls_path, class:"btn btn-primary btn-lg"%>
</div>

<% else %>

<div class="container pt-5">
    <div class="row text-center">
        <h1 class="mx-auto">Welcome</h1>

    </div>
    <div class="row text-center">
        <h5 class="mx-auto">Please fill out the below form to start making calls</h5>
    </div>

    <div class="row justify-content-center">
        <div class="col-6 signup-card">
            <div class="w-100 justify-content-center d-flex">
                <%=image_tag "/assets/logo.png", id:"logo"%>
            </div>

            <%= form_with(model: @user, local: true, action:"create") do |form| %>
            <% if @user.errors.any? %>
                <div id="error_explanation">
                    <h5><%= pluralize(@user.errors.count, "error") %>
                        prohibited this user from being saved:</h5>
                    <ul>
                        <% @user.errors.full_messages.each do |message| %>
                            <li><%= message %></li>
                        <% end %>
                    </ul>
                </div>
            <% end %>
            <form>
                <div class="form-group">
                    <div class="input-group">
                        <div class="input-group-prepend">
                            <span class="input-group-text">
                                <i class="fa fa-envelope"></i>
                            </span>
                        </div>
                        <%= form.text_field :email, placeholder:"Email", autocomplete:"", required:"true", type:"email", class:"form-control input-group-form" %>
                    </div>
                    <small id="emailHelp" class="form-text text-muted">We'll never share your email with anyone else.</small>
                    <!-- input-group.// -->
                </div>
                <!-- form-group// -->
                <div class="form-group">
                    <div class="input-group">
                        <div class="input-group-prepend">
                            <span class="input-group-text">
                                <i class="fas fa-user"></i>
                            </span>
                        </div>
                        <%= form.text_field :name, placeholder:"Name", required:"true", autocomplete:"", type:"text", class:"form-control" %>
                    </div>
                    <!-- input-group.// -->
                </div>
                <div class="form-group">
                    <div class="input-group">
                        <div class="input-group-prepend">
                            <span class="input-group-text">
                                <i class="fas fa-phone"></i>
                            </span>
                        </div>
                        <%= form.text_field :phone, placeholder:"Phone Number 123-123-1234", required:"true", autocomplete:"", type:"tel", class:"form-control", pattern: "[0-9]{3}-[0-9]{3}-[0-9]{4}" %>
                    </div>
                    <!-- input-group.// -->
                </div>
                <!-- form-group// -->
                <div class="form-group">
                    <%= form.submit "Login", :class=>"btn btn-block btn-primary" %>
                </div>
                <!-- form-group// -->
            </form>
        <% end %>
    </div>
</div>



<% end %>

app/views/voters/index.html.erb
<div class="container-fluid voter-table-card mt-5">
    <div class="row">
        <div class="w-100 justify-content-center d-flex pb-4">
            <%=image_tag asset_path("logo.png"), id:"logo"%>
        </div>
        <h4 class="text-center w-100">Your Call List</h4>
    </div>
    <div class="row mb-4">
        <%= link_to "Home", root_path, class:"btn btn-primary mx-1"%>
        <%= link_to "Make a Call", calls_path, class:"btn btn-primary mx-1"%>
    </div>
    <% if current_user.admin? %>
    <div class="row mb-4">
        <%= form_tag import_voters_path, multipart: true do %>
            <%= file_field_tag :file, class:"btn btn-dark" %>
            <%= submit_tag "Import", class:"btn btn-warning" %>
        <% end %>
    </div>
    <%end %>
    <div class="row">
        <h5>Calls made: <%=current_user.stats%></h5>
        <input class="form-control" id="voterSearch" type="text" placeholder="Search...">
        <div class="table mt-3 mx-5">
            <table class="table">
                <thead>
                    <tr>
                        <th scope="col">Name</th>
                        <th scope="col" style="width:20%">Address</th>
                        <th scope="col" >Number</th>
                        <th scope="col">Status</th>
                        <th scope="col">Support</th>
                        <th scope="col">Yard Sign</th>
                        <th scope="col">Volunteer</th>
                        <th scope="col">Caller</th>
                    </tr>
                </thead>
                <tbody id="voter-table">
                    <% @voters.order('voters.status ASC').each do |v| %>
                        <tr>
                            <td scope="row"><%=v.name%></td>
                            <td><%=v.full_address%></td>
                            <td><%=v.format_phone%></td>
                            <td><%=v.status%></td>
                            <td><%=v.support%></td>
                            <td><%=v.sign%></td>
                            <td><%=v.volunteer%></td>
                            <td><%=v.user.name%></td>
                            <% if current_user.admin? %>
                                <td><%=link_to "Voter", calls_path(voter_id: v.id), class:"btn btn-primary"%></td>
                            <% end %>

                        </tr>
                    <% end %>
                </tbody>
            </table>
        </div>
    </div>
</div>

app/views/voters/new.html.erb
<div class="container voter-table-card mt-5">
    <div class="row">
        <div class="w-100 justify-content-center d-flex pb-4">
            <%=image_tag asset_path("logo.png"), id:"logo"%>
        </div>
        <h3 class="text-center w-100">Add New Voter</h3>
    </div>
    <div class="row">
        <div class="col">

        </div>
        <div class="col-6">
            <%= form_for @voter do |f| %>
            <% if @voter.errors.any? %>
                <div id="error_explanation">
                    <h5><%= pluralize(@voter.errors.count, "error") %>
                        prohibited this user from being saved:</h5>
                    <ul>
                        <% @voter.errors.full_messages.each do |message| %>
                            <li><%= message %></li>
                        <% end %>
                    </ul>
                </div>
            <% end %>
            <form>
                <div class="form-group">
                    <div class="input-group">
                        <div class="input-group-prepend">
                            <span class="input-group-text">
                                <i class="fa fa-envelope"></i>
                            </span>
                        </div>
                        <%= f.text_field :email, placeholder:"Email", autocomplete:"", required:"true", type:"email", class:"form-control input-group-form" %>
                    </div>
                    <!-- input-group.// -->
                </div>
                <!-- form-group// -->
                <div class="form-group">
                    <div class="input-group">
                        <div class="input-group-prepend">
                            <span class="input-group-text">
                                <i class="fas fa-user"></i>
                            </span>
                        </div>
                        <%= f.text_field :name, placeholder:"Name", required:"true", autocomplete:"", type:"text", class:"form-control" %>
                    </div>
                    <!-- input-group.// -->
                </div>
                <div class="form-group">
                    <div class="input-group">
                        <div class="input-group-prepend">
                            <span class="input-group-text">
                                <i class="fas fa-phone"></i>
                            </span>
                        </div>
                        <%= f.text_field :phone, placeholder:"Phone Number 123-123-1234", required:"true", autocomplete:"", type:"tel", class:"form-control", pattern: "[0-9]{3}-[0-9]{3}-[0-9]{4}" %>
                    </div>
                    <!-- input-group.// -->
                </div>

                <div class="form-group">
                    <div class="input-group">
                        <div class="input-group-prepend">
                            <span class="input-group-text">
                                <i class="fas fa-home"></i>
                            </span>
                        </div>
                        <%= f.text_field :address, placeholder:"Address", required:"true", autocomplete:"", type:"text",class:"form-control", value:"" %>
                    </div>
                    <!-- input-group.// -->
                </div>
                <!-- form-group// -->
                <div class="form-group d-flex">
                    <%= link_to "Cancel", root_path, class:"btn btn-danger mr-1"%>
                    <%= f.submit "Add Voter", :class=>"btn btn-block btn-primary" %>
                </div>
                <!-- form-group// -->
            </form>
            <%end%>
        </div>
        <div class="col">

        </div>

    </div>
</div>

app/views/welcome/index.html.erb
<% if alert %>
<p id="alert" class="alert alert-warning text-center"><%= alert %></p>
<% end %>


<% unless current_user.nil? %>
<div class="welcome-card centered text-center">
    <div class="w-100 justify-content-center d-flex pb-4">
        <%=image_tag asset_path("logo.png"), id:"logo"%>
    </div>
    <h4 class="pb-1">Hello <%=current_user.name%></h4>
    <div class="d-flex flex-column">
        <%= link_to "Start Making Calls!", calls_path, class:"btn btn-success my-2"%>
        <%= link_to "Your Call List", voters_path, class:"btn btn-primary my-2"%>
        <%= link_to "DEMO Call Sheet", walkthrough_path, class:"btn btn-primary my-2"%>
    </div>

</div>

<% else %>

<div class="container pt-5">
    <div class="row text-center">
        <h1 class="mx-auto">Welcome</h1>

    </div>
    <div class="row text-center">
        <h5 class="mx-auto">Please fill out the below form to start making calls</h5>
    </div>

    <div class="row justify-content-center">
        <div class="col-lg-6 signup-card">
            <div class="w-100 justify-content-center d-flex pb-2">
                <%=image_tag "/assets/logo.png", id:"logo"%>
            </div>

            <%= form_with(model: @user, local: true) do |form| %>
            <% if @user %>
            <% if @user.errors.any? %>
                <div id="error_explanation">
                    <h5><%= pluralize(@user.errors.count, "error") %>
                        prohibited this user from being saved:</h5>
                    <ul>
                        <% @user.errors.full_messages.each do |message| %>
                            <li><%= message %></li>
                        <% end %>
                    </ul>
                </div>
            <% end %>
            <%end %>

            <form>
                <!-- form-group// -->
                <div class="form-group">
                    <div class="input-group">
                        <div class="input-group-prepend">
                            <span class="input-group-text">
                                <i class="fas fa-user"></i>
                            </span>
                        </div>
                        <%= form.text_field :name, placeholder:"Name", required:"true", autocomplete:"", type:"text", class:"form-control" %>
                    </div>
                    <!-- input-group.// -->
                </div>
                <div class="form-group">
                    <div class="input-group">
                        <div class="input-group-prepend">
                            <span class="input-group-text">
                                <i class="fa fa-envelope"></i>
                            </span>
                        </div>
                        <%= form.text_field :email, placeholder:"Email", autocomplete:"", required:"true", type:"email", class:"form-control input-group-form" %>
                    </div>
                    <small id="emailHelp" class="form-text text-muted">We'll never share your email with anyone else.</small>
                    <!-- input-group.// -->
                </div>

                <div class="form-group">
                    <div class="input-group">
                        <div class="input-group-prepend">
                            <span class="input-group-text">
                                <i class="fas fa-phone"></i>
                            </span>
                        </div>
                        <%= form.number_field :phone, placeholder:"Phone Number: 5125554823", required:"true", autocomplete:"", type:"tel", class:"form-control", pattern: "[0-9]{3}[0-9]{3}[0-9]{4}" %>
                    </div>
                    <!-- input-group.// -->
                </div>
                <!-- form-group// -->
                <div class="form-group">
                    <%= form.submit "Login", :class=>"btn btn-block btn-primary" %>
                </div>
                <!-- form-group// -->
            </form>
        <% end %>
    </div>
</div>



<% end %>